---
sudo:     false
language: ruby
cache:    bundler
script:
  - bundle exec rspec
  - bundle exec rubocop
rvm:
  - '2.3.0'
  - '2.4.0'
  - ruby-head
before_install: gem install bundler -v 1.12.5
matrix:
  allow_failures:
    - rvm: ruby-head
