---
sudo:     false
language: ruby
cache:    bundler
script:
  - bundle exec rspec
  - bundle exec rubocop
rvm:
  - 2.3.0
  - ruby-head
before_install: gem install bundler
matrix:
  allow_failures:
    - rvm: ruby-head
